apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildbot.fullname" . }}-master-pb
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: buildbot-master
{{- with .Values.servicePB.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.servicePB.type }}
  ports:
    - port: {{ .Values.servicePB.port }}
      targetPort: pb
      protocol: TCP
      name: pb
  selector:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: buildbot-master
