{{- if not .Values.password.secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildbot-worker.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "buildbot-worker.name" . }}
    helm.sh/chart: {{ include "buildbot-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.password.value }}
  {{ .Values.password.key }}: {{ .Values.password.value | b64enc | quote }}
{{- else }}
  {{ .Values.password.key }}: {{ randAlphaNum 10 |b64enc | quote }}
{{- end }}
{{- end }}
